'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import { Button, Container, Divider, Grid, Stack, Typography } from '@mui/material'
import { useGetters } from '@/store/store'
import { topics } from '@/constant'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props {
  children: React.ReactNode
}

const RootLayout = ({ children }: Props): JSX.Element => {
  const { currentTopic } = useGetters()
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body>
        <Container style={{ paddingTop: 10 }}>
          <Grid container spacing={2}
            alignItems="center">
            <Grid item xs={8}>
              <Typography variant="h1" gutterBottom>
                Portfolio
              </Typography>
            </Grid>
            <Grid item xs={4}>
              <Stack spacing={2} direction="row"
                divider={<Divider orientation="vertical" flexItem />}
                justifyContent="right"
                alignItems="right">
                <Button variant={currentTopic === topics.Home ? 'contained' : 'outlined'} size='large' sx={{width:"100%"}}>Home</Button>
                <Button variant='outlined' size='large' sx={{width:"100%"}}>Games</Button>
                <Button variant='outlined' size='large' sx={{width:"100%"}}>Critical Analysis</Button>
              </Stack>
            </Grid>
          </Grid>
          {children}
        </Container>
      </body>
    </html>
  )
}

export default RootLayout
